name: Build

on:
  push:
    branches:
      - main  # 可以根据需要修改触发条件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build child_test submodule
      run: |
        cd packages/child_test
        pnpm install
        pnpm run build
        mv dist ../
        
    - name: Build child_main
      run: |
        cd packages/child_main
        pnpm install
        pnpm run build
