name: Build

on:
  push:
    branches:
      - main  # 可以根据需要修改触发条件

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm 
      run: npm install pnpm -g
      
    - name: pnpm -V
      run: pnpm -V

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build:test
